# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew SetupCIWorkspace :build
    - name: copy world file
      run: cp ci/world.zip build/libs/world.zip
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs

  test: 
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        sleep_time:
          - '0s'
          - '2s'
          - '40t'
          - 'before world'
        version:
          - '8:1.7.10-10.13.4.1614-1.7.10'
          - '8:1.8.9-11.15.1.2318-1.8.9'
          - '8:1.9.4-12.17.0.2317-1.9.4'
          - '8:1.10.2-12.18.3.2511'
          # 1.11.2 can't be supported because installer was broken.
          # - '8:1.11.2-13.20.1.2588'
          - '8:1.12.2-14.23.5.2860'
          - '8:1.13.2-25.0.223'
          - '8:1.14.4-28.2.26'
          - '8:1.15.2-31.2.57'
          - '8:1.16.5-36.2.29'
          - '17:1.17.1-37.1.1'
          - '17:1.18.1-39.0.88'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Package
          path: libs
      - name: Configure Version
        id: configure_version
        env:
          VERSION: ${{ matrix.version }}
        run: |
          MC_VERSION="${VERSION#*:}"
          JAVA_VERSION="${VERSION%%:*}"
          JAR_NAME="$(ls libs | grep "^minecraft-server-auto-closer-[0-9.]*.jar$")"
          echo "::set-output name=java_version::$JAVA_VERSION"
          echo "::set-output name=mc_version::$MC_VERSION"
          echo "::set-output name=jar_name::$JAR_NAME"

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ steps.configure_version.outputs.java_version }}

      - name: decompress world file
        run: unzip libs/world.zip

      - uses: anatawa12/minecraft-server-start-test@v1
        with:
          version: ${{ steps.configure_version.outputs.mc_version }}
          sleep_time: ${{ matrix.sleep_time }}
          world_data: ./world
          minecraft_server_auto_closer_path:
            ./libs/${{ steps.configure_version.outputs.jar_name }}
